
import React from 'react';
import Halo from '../components/Halo';
import './Architexture.scss';
import { model1 } from '../data.json';
import Project from '../components/Project';

function Architexture() {
    return (


  <div id="container">
    <div id="stage">
        <div id="form-1">
            <div id="hi-box" class="cube backfaces">
                <div class="inner">
                    <div class="plane seven cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane eight cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane ten cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane twelve cold inter">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                </div>
                <div class="outer">
                    <div class="plane five cold hole"><!-- coldhole--></div>
                    <div class="plane three hot hole"><!-- hothole--></div>
                    <div class="plane one hot">content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make</div>
                    <div class="plane two hot">content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make</div>
                    <div class="plane four hot">content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make</div>
                </div>
            </div>

            <div id="mid-box" class="cube backfaces">
                <div class="inner">
                    <div class="plane three cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane five cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane seven hot inter">content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                </div>
                <div class="outer">
                    <div class="plane two hot hole"><!-- hole--></div>
                    <div class="plane four hot hole"><!-- hole--></div>
                    <div class="plane nine hot">make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                    <div class="plane twelve hot inter">content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                    <div class="plane eleven hot">make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                </div>
            </div>

            <div id="low-box" class="cube backfaces">
                <div class="inner">
                    <div class="plane two hot">make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                    <div class="plane six hot">make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                    <div class="plane four hot">make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make content to make </div>
                </div>
                <div class="outer">    
                    <div class="plane seven cold inter">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane eight cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane twelve cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                    <div class="plane ten cold">having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are having trouble understanding why you are </div>
                </div>
            </div>

        </div>
    </div>
  </div>
  


  );
}
export default Architexture;
